version: '3.1'

services:
  tg:
    container_name: tg_bot
    build: tg/
    restart: always
    ports:
      - "8081:8081"

  web:
    container_name: web
    build: web/
    restart: always
    ports:
      - "8000:8000"